"""initial migration

Revision ID: 56fc27e9c1ad
Revises: 7554f1156f3a
Create Date: 2026-07-10 19:15:51.263290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fc27e9c1ad'
down_revision = '7554f1156f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('pai', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('instrumento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coord', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sei', sa.String(), nullable=True),
    sa.Column('contraparte', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('descri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    with op.batch_alter_table('instrumento', schema='dem') as batch_op:
        batch_op.create_index(batch_op.f('ix_dem_instrumento_sei'), ['sei'], unique=True)

    op.create_table('log_desc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_registro', sa.String(), nullable=False),
    sa.Column('desc_registro', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('plano_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_sigla', sa.String(), nullable=False),
    sa.Column('atividade_desc', sa.String(), nullable=False),
    sa.Column('natureza', sa.String(), nullable=False),
    sa.Column('meta', sa.Float(), nullable=False),
    sa.Column('situa', sa.String(), nullable=True),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_sistema', sa.String(), nullable=False),
    sa.Column('descritivo', sa.Text(), nullable=False),
    sa.Column('funcionalidade_conv', sa.Integer(), nullable=True),
    sa.Column('funcionalidade_acordo', sa.Integer(), nullable=True),
    sa.Column('funcionalidade_instru', sa.Integer(), nullable=True),
    sa.Column('carga_auto', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('tipos_demanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('relevancia', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('despacha', sa.Integer(), nullable=True),
    sa.Column('email_confirmation_sent_on', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed', sa.Integer(), nullable=True),
    sa.Column('email_confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('last_logged_in', sa.DateTime(), nullable=True),
    sa.Column('current_logged_in', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('coord', sa.String(), nullable=True),
    sa.Column('despacha2', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('sversion', sa.String(), nullable=True),
    sa.Column('cargo_func', sa.String(), nullable=True),
    sa.Column('trab_conv', sa.Integer(), nullable=True),
    sa.Column('trab_acordo', sa.Integer(), nullable=True),
    sa.Column('despacha0', sa.Integer(), nullable=True),
    sa.Column('trab_instru', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    with op.batch_alter_table('users', schema='dem') as batch_op:
        batch_op.create_index(batch_op.f('ix_dem_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_dem_users_username'), ['username'], unique=True)

    op.create_table('ativ_usu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['dem.plano_trabalho.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dem.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('demandas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programa', sa.Integer(), nullable=False),
    sa.Column('sei', sa.String(), nullable=False),
    sa.Column('convênio', sa.String(), nullable=True),
    sa.Column('ano_convênio', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=140), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('necessita_despacho', sa.Integer(), nullable=True),
    sa.Column('conclu', sa.String(), nullable=True),
    sa.Column('data_conclu', sa.DateTime(), nullable=True),
    sa.Column('necessita_despacho_cg', sa.Integer(), nullable=True),
    sa.Column('urgencia', sa.Integer(), nullable=True),
    sa.Column('data_env_despacho', sa.DateTime(), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('data_verific', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dem.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('passos_tipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('passo', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['dem.tipos_demanda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('despachos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('demanda_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('passo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['demanda_id'], ['dem.demandas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['dem.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('log_auto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('demanda_id', sa.Integer(), nullable=True),
    sa.Column('tipo_registro', sa.Text(), nullable=False),
    sa.Column('atividade', sa.Integer(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atividade'], ['dem.plano_trabalho.id'], ),
    sa.ForeignKeyConstraint(['demanda_id'], ['dem.demandas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dem.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('msgs_recebidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('demanda_id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['demanda_id'], ['dem.demandas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dem.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('providencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('demanda_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('programada', sa.Integer(), nullable=True),
    sa.Column('passo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['demanda_id'], ['dem.demandas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providencias', schema='dem')
    op.drop_table('msgs_recebidas', schema='dem')
    op.drop_table('log_auto', schema='dem')
    op.drop_table('despachos', schema='dem')
    op.drop_table('passos_tipos', schema='dem')
    op.drop_table('demandas', schema='dem')
    op.drop_table('ativ_usu', schema='dem')
    with op.batch_alter_table('users', schema='dem') as batch_op:
        batch_op.drop_index(batch_op.f('ix_dem_users_username'))
        batch_op.drop_index(batch_op.f('ix_dem_users_email'))

    op.drop_table('users', schema='dem')
    op.drop_table('tipos_demanda', schema='dem')
    op.drop_table('sistema', schema='dem')
    op.drop_table('plano_trabalho', schema='dem')
    op.drop_table('log_desc', schema='dem')
    with op.batch_alter_table('instrumento', schema='dem') as batch_op:
        batch_op.drop_index(batch_op.f('ix_dem_instrumento_sei'))

    op.drop_table('instrumento', schema='dem')
    op.drop_table('coords', schema='dem')
    # ### end Alembic commands ###
