"""initial migration

Revision ID: 7554f1156f3a
Revises: 
Create Date: 2026-07-10 19:13:26.308572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7554f1156f3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acordos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sei', sa.String(), nullable=True),
    sa.Column('epe', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor_cnpq', sa.Float(), nullable=True),
    sa.Column('valor_epe', sa.Float(), nullable=True),
    sa.Column('unidade_cnpq', sa.String(), nullable=True),
    sa.Column('situ', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('capital', sa.Float(), nullable=True),
    sa.Column('custeio', sa.Float(), nullable=True),
    sa.Column('bolsas', sa.Float(), nullable=True),
    sa.Column('siafi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acordos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acordos_sei'), ['sei'], unique=True)

    op.create_table('bolsas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod', sa.String(), nullable=False),
    sa.Column('niv', sa.String(), nullable=True),
    sa.Column('mensalidade', sa.Float(), nullable=True),
    sa.Column('auxilio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capital_custeio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_acordo', sa.Integer(), nullable=True),
    sa.Column('capital_pg', sa.Float(), nullable=True),
    sa.Column('custeio_pg', sa.Float(), nullable=True),
    sa.Column('bolsa_pg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chamadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sei', sa.String(), nullable=False),
    sa.Column('chamada', sa.String(), nullable=True),
    sa.Column('qtd_projetos', sa.Integer(), nullable=True),
    sa.Column('vl_total_chamada', sa.Float(), nullable=True),
    sa.Column('doc_sei', sa.String(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('id_relaciona', sa.String(), nullable=True),
    sa.Column('qtd_processos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chamadas_cnpq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('cod_programa', sa.String(), nullable=True),
    sa.Column('id_dw', sa.Integer(), nullable=True),
    sa.Column('qtd_processos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chamadas_cnpq_acordos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acordo_id', sa.Integer(), nullable=True),
    sa.Column('chamada_cnpq_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convenio',
    sa.Column('NR_CONVENIO', sa.String(), nullable=False),
    sa.Column('ID_PROPOSTA', sa.String(), nullable=True),
    sa.Column('DIA', sa.String(), nullable=True),
    sa.Column('MES', sa.String(), nullable=True),
    sa.Column('ANO', sa.String(), nullable=True),
    sa.Column('DIA_ASSIN_CONV', sa.String(), nullable=True),
    sa.Column('SIT_CONVENIO', sa.String(), nullable=True),
    sa.Column('SUBSITUACAO_CONV', sa.String(), nullable=True),
    sa.Column('SITUACAO_PUBLICACAO', sa.String(), nullable=True),
    sa.Column('INSTRUMENTO_ATIVO', sa.String(), nullable=True),
    sa.Column('IND_OPERA_OBTV', sa.String(), nullable=True),
    sa.Column('NR_PROCESSO', sa.String(), nullable=True),
    sa.Column('UG_EMITENTE', sa.String(), nullable=True),
    sa.Column('DIA_PUBL_CONV', sa.String(), nullable=True),
    sa.Column('DIA_INIC_VIGENC_CONV', sa.String(), nullable=True),
    sa.Column('DIA_FIM_VIGENC_CONV', sa.Date(), nullable=True),
    sa.Column('DIA_FIM_VIGENC_ORIGINAL_CONV', sa.String(), nullable=True),
    sa.Column('DIAS_PREST_CONTAS', sa.String(), nullable=True),
    sa.Column('DIA_LIMITE_PREST_CONTAS', sa.String(), nullable=True),
    sa.Column('SITUACAO_CONTRATACAO', sa.String(), nullable=True),
    sa.Column('IND_ASSINADO', sa.String(), nullable=True),
    sa.Column('MOTIVO_SUSPENSAO', sa.String(), nullable=True),
    sa.Column('IND_FOTO', sa.String(), nullable=True),
    sa.Column('QTDE_CONVENIOS', sa.String(), nullable=True),
    sa.Column('QTD_TA', sa.String(), nullable=True),
    sa.Column('QTD_PRORROGA', sa.String(), nullable=True),
    sa.Column('VL_GLOBAL_CONV', sa.Float(), nullable=True),
    sa.Column('VL_REPASSE_CONV', sa.Float(), nullable=True),
    sa.Column('VL_CONTRAPARTIDA_CONV', sa.Float(), nullable=True),
    sa.Column('VL_EMPENHADO_CONV', sa.Float(), nullable=True),
    sa.Column('VL_DESEMBOLSADO_CONV', sa.Float(), nullable=True),
    sa.Column('VL_SALDO_REMAN_TESOURO', sa.Float(), nullable=True),
    sa.Column('VL_SALDO_REMAN_CONVENENTE', sa.Float(), nullable=True),
    sa.Column('VL_RENDIMENTO_APLICACAO', sa.Float(), nullable=True),
    sa.Column('VL_INGRESSO_CONTRAPARTIDA', sa.Float(), nullable=True),
    sa.Column('VL_SALDO_CONTA', sa.Float(), nullable=True),
    sa.Column('VALOR_GLOBAL_ORIGINAL_CONV', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('NR_CONVENIO')
    )
    op.create_table('crono_desemb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ID_PROPOSTA', sa.String(), nullable=True),
    sa.Column('NR_CONVENIO', sa.String(), nullable=True),
    sa.Column('NR_PARCELA_CRONO_DESEMBOLSO', sa.String(), nullable=True),
    sa.Column('MES_CRONO_DESEMBOLSO', sa.String(), nullable=True),
    sa.Column('ANO_CRONO_DESEMBOLSO', sa.String(), nullable=True),
    sa.Column('TIPO_RESP_CRONO_DESEMBOLSO', sa.String(), nullable=True),
    sa.Column('VALOR_PARCELA_CRONO_DESEMBOLSO', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dados_sei',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr_convenio', sa.String(), nullable=False),
    sa.Column('sei', sa.String(), nullable=False),
    sa.Column('epe', sa.String(), nullable=False),
    sa.Column('fiscal', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dados_sei', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dados_sei_sei'), ['sei'], unique=True)

    op.create_table('coords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('pai', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('instrumento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coord', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sei', sa.String(), nullable=True),
    sa.Column('contraparte', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('descri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    with op.batch_alter_table('instrumento', schema='dem') as batch_op:
        batch_op.create_index(batch_op.f('ix_dem_instrumento_sei'), ['sei'], unique=True)

    op.create_table('log_desc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_registro', sa.String(), nullable=False),
    sa.Column('desc_registro', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('plano_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_sigla', sa.String(), nullable=False),
    sa.Column('atividade_desc', sa.String(), nullable=False),
    sa.Column('natureza', sa.String(), nullable=False),
    sa.Column('meta', sa.Float(), nullable=False),
    sa.Column('situa', sa.String(), nullable=True),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_sistema', sa.String(), nullable=False),
    sa.Column('descritivo', sa.Text(), nullable=False),
    sa.Column('funcionalidade_conv', sa.Integer(), nullable=True),
    sa.Column('funcionalidade_acordo', sa.Integer(), nullable=True),
    sa.Column('funcionalidade_instru', sa.Integer(), nullable=True),
    sa.Column('carga_auto', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('tipos_demanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('relevancia', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('despacha', sa.Integer(), nullable=True),
    sa.Column('email_confirmation_sent_on', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed', sa.Integer(), nullable=True),
    sa.Column('email_confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('last_logged_in', sa.DateTime(), nullable=True),
    sa.Column('current_logged_in', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('coord', sa.String(), nullable=True),
    sa.Column('despacha2', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=True),
    sa.Column('sversion', sa.String(), nullable=True),
    sa.Column('cargo_func', sa.String(), nullable=True),
    sa.Column('trab_conv', sa.Integer(), nullable=True),
    sa.Column('trab_acordo', sa.Integer(), nullable=True),
    sa.Column('despacha0', sa.Integer(), nullable=True),
    sa.Column('trab_instru', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    with op.batch_alter_table('users', schema='dem') as batch_op:
        batch_op.create_index(batch_op.f('ix_dem_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_dem_users_username'), ['username'], unique=True)

    op.create_table('desembolso',
    sa.Column('ID_DESEMBOLSO', sa.String(), nullable=False),
    sa.Column('NR_CONVENIO', sa.String(), nullable=True),
    sa.Column('DT_ULT_DESEMBOLSO', sa.Date(), nullable=True),
    sa.Column('QTD_DIAS_SEM_DESEMBOLSO', sa.String(), nullable=True),
    sa.Column('DATA_DESEMBOLSO', sa.Date(), nullable=True),
    sa.Column('ANO_DESEMBOLSO', sa.String(), nullable=True),
    sa.Column('MES_DESEMBOLSO', sa.String(), nullable=True),
    sa.Column('NR_SIAFI', sa.String(), nullable=True),
    sa.Column('VL_DESEMBOLSADO', sa.Float(), nullable=True),
    sa.Column('ID_EMPENHO', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID_DESEMBOLSO')
    )
    op.create_table('emp_cap_cus',
    sa.Column('id_empenho', sa.String(), nullable=False),
    sa.Column('nd', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_empenho')
    )
    op.create_table('empenho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ID_EMPENHO', sa.String(), nullable=True),
    sa.Column('NR_CONVENIO', sa.String(), nullable=True),
    sa.Column('NR_EMPENHO', sa.String(), nullable=True),
    sa.Column('TIPO_NOTA', sa.String(), nullable=True),
    sa.Column('DESC_TIPO_NOTA', sa.String(), nullable=True),
    sa.Column('DATA_EMISSAO', sa.Date(), nullable=True),
    sa.Column('COD_SITUACAO_EMPENHO', sa.String(), nullable=True),
    sa.Column('DESC_SITUACAO_EMPENHO', sa.String(), nullable=True),
    sa.Column('VALOR_EMPENHO', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financeiro_acordo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_acordo', sa.Integer(), nullable=True),
    sa.Column('qtd_item_despesa', sa.Float(), nullable=True),
    sa.Column('valor_total_item_despesa', sa.Float(), nullable=True),
    sa.Column('cod_fonte_recurso', sa.String(), nullable=True),
    sa.Column('nme_fonte_recurso', sa.String(), nullable=True),
    sa.Column('cod_plano_interno', sa.String(), nullable=True),
    sa.Column('nme_plano_interno', sa.String(), nullable=True),
    sa.Column('nme_categ_economica', sa.String(), nullable=True),
    sa.Column('nme_natur_desp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_programa_cnpq',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('id_acordo', sa.Integer(), nullable=True),
    sa.Column('id_programa', sa.Integer(), nullable=True),
    sa.Column('cod_programa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_table('msg_siconv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr_convenio', sa.String(length=6), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('data_ref', sa.Date(), nullable=True),
    sa.Column('sit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NR_CONVENIO', sa.String(), nullable=True),
    sa.Column('IDENTIF_FORNECEDOR', sa.String(), nullable=True),
    sa.Column('NOME_FORNECEDOR', sa.String(), nullable=True),
    sa.Column('VL_PAGO', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentospdctr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sexo_proc_filho', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('situ_filho', sa.String(), nullable=True),
    sa.Column('data_situ_filho', sa.Date(), nullable=True),
    sa.Column('inic_filho', sa.Date(), nullable=True),
    sa.Column('term_filho', sa.Date(), nullable=True),
    sa.Column('proc_mae', sa.String(), nullable=True),
    sa.Column('coordenador', sa.String(), nullable=True),
    sa.Column('inic_mae', sa.Date(), nullable=True),
    sa.Column('term_mae', sa.Date(), nullable=True),
    sa.Column('titu_proc_filho', sa.String(), nullable=True),
    sa.Column('nome_chamada', sa.String(), nullable=True),
    sa.Column('modalidade', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('cod_programa', sa.String(), nullable=True),
    sa.Column('grande_area', sa.String(), nullable=True),
    sa.Column('area_conhecimento', sa.String(), nullable=True),
    sa.Column('sigla_inst', sa.String(), nullable=True),
    sa.Column('uf_inst', sa.String(), nullable=True),
    sa.Column('cidade_inst', sa.String(), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('tipo_pagamento', sa.String(), nullable=True),
    sa.Column('valor_pago', sa.Float(), nullable=True),
    sa.Column('situ_mae', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_aplic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ID_PROPOSTA', sa.String(), nullable=True),
    sa.Column('NATUREZA_AQUISICAO', sa.String(), nullable=True),
    sa.Column('TIPO_DESPESA_ITEM', sa.String(), nullable=True),
    sa.Column('COD_NATUREZA_DESPESA', sa.String(), nullable=True),
    sa.Column('QTD_ITEM', sa.Float(), nullable=True),
    sa.Column('VALOR_UNITARIO_ITEM', sa.Float(), nullable=True),
    sa.Column('VALOR_TOTAL_ITEM', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processo_filho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_programa', sa.String(), nullable=True),
    sa.Column('nome_chamada', sa.String(), nullable=True),
    sa.Column('proc_mae', sa.String(), nullable=True),
    sa.Column('processo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('modalidade', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('situ_filho', sa.String(), nullable=True),
    sa.Column('inic_filho', sa.Date(), nullable=True),
    sa.Column('term_filho', sa.Date(), nullable=True),
    sa.Column('mens_pagas', sa.Integer(), nullable=True),
    sa.Column('pago_total', sa.Float(), nullable=True),
    sa.Column('valor_apagar', sa.Float(), nullable=True),
    sa.Column('mens_apagar', sa.Integer(), nullable=True),
    sa.Column('dt_ult_pag', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processo_mae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_programa', sa.String(), nullable=True),
    sa.Column('nome_chamada', sa.String(), nullable=True),
    sa.Column('proc_mae', sa.String(), nullable=True),
    sa.Column('inic_mae', sa.Date(), nullable=True),
    sa.Column('term_mae', sa.Date(), nullable=True),
    sa.Column('coordenador', sa.String(), nullable=True),
    sa.Column('situ_mae', sa.String(), nullable=True),
    sa.Column('id_chamada', sa.Integer(), nullable=True),
    sa.Column('pago_capital', sa.Float(), nullable=True),
    sa.Column('pago_custeio', sa.Float(), nullable=True),
    sa.Column('pago_bolsas', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programa',
    sa.Column('ID_PROGRAMA', sa.String(), nullable=False),
    sa.Column('COD_PROGRAMA', sa.String(), nullable=True),
    sa.Column('NOME_PROGRAMA', sa.String(), nullable=True),
    sa.Column('SIT_PROGRAMA', sa.String(), nullable=True),
    sa.Column('ANO_DISPONIBILIZACAO', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID_PROGRAMA')
    )
    op.create_table('programa_cnpq',
    sa.Column('ID_PROGRAMA', sa.Integer(), nullable=False),
    sa.Column('COD_PROGRAMA', sa.String(), nullable=True),
    sa.Column('NOME_PROGRAMA', sa.String(), nullable=True),
    sa.Column('SIGLA_PROGRAMA', sa.String(), nullable=True),
    sa.Column('COORD', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID_PROGRAMA')
    )
    op.create_table('programas_a_pegar',
    sa.Column('cod_programa', sa.String(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('coord', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cod_programa')
    )
    op.create_table('proposta',
    sa.Column('ID_PROGRAMA', sa.String(), nullable=True),
    sa.Column('ID_PROPOSTA', sa.String(), nullable=False),
    sa.Column('UF_PROPONENTE', sa.String(), nullable=True),
    sa.Column('NM_PROPONENTE', sa.String(), nullable=True),
    sa.Column('OBJETO_PROPOSTA', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID_PROPOSTA')
    )
    op.create_table('ref_pag_pdctr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_siconv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=True),
    sa.Column('cod_inst', sa.String(), nullable=True),
    sa.Column('data_cha_dw', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acordo_procmae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acordo_id', sa.Integer(), nullable=False),
    sa.Column('proc_mae_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acordo_id'], ['acordos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proc_mae_id'], ['processo_mae.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ativ_usu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['dem.plano_trabalho.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dem.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('demandas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programa', sa.Integer(), nullable=False),
    sa.Column('sei', sa.String(), nullable=False),
    sa.Column('convênio', sa.String(), nullable=True),
    sa.Column('ano_convênio', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=140), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('necessita_despacho', sa.Integer(), nullable=True),
    sa.Column('conclu', sa.String(), nullable=True),
    sa.Column('data_conclu', sa.DateTime(), nullable=True),
    sa.Column('necessita_despacho_cg', sa.Integer(), nullable=True),
    sa.Column('urgencia', sa.Integer(), nullable=True),
    sa.Column('data_env_despacho', sa.DateTime(), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('data_verific', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dem.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('passos_tipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('passo', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['dem.tipos_demanda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('homologados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamada_id', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.String(), nullable=True),
    sa.Column('nota', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('mod', sa.String(), nullable=True),
    sa.Column('niv', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['chamada_id'], ['chamadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despachos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('demanda_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('passo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['demanda_id'], ['dem.demandas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['dem.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('log_auto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('demanda_id', sa.Integer(), nullable=True),
    sa.Column('tipo_registro', sa.Text(), nullable=False),
    sa.Column('atividade', sa.Integer(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atividade'], ['dem.plano_trabalho.id'], ),
    sa.ForeignKeyConstraint(['demanda_id'], ['dem.demandas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dem.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('msgs_recebidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('demanda_id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['demanda_id'], ['dem.demandas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dem.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    op.create_table('providencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('demanda_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('programada', sa.Integer(), nullable=True),
    sa.Column('passo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['demanda_id'], ['dem.demandas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dem'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providencias', schema='dem')
    op.drop_table('msgs_recebidas', schema='dem')
    op.drop_table('log_auto', schema='dem')
    op.drop_table('despachos', schema='dem')
    op.drop_table('homologados')
    op.drop_table('passos_tipos', schema='dem')
    op.drop_table('demandas', schema='dem')
    op.drop_table('ativ_usu', schema='dem')
    op.drop_table('acordo_procmae')
    op.drop_table('ref_siconv')
    op.drop_table('ref_pag_pdctr')
    op.drop_table('proposta')
    op.drop_table('programas_a_pegar')
    op.drop_table('programa_cnpq')
    op.drop_table('programa')
    op.drop_table('processo_mae')
    op.drop_table('processo_filho')
    op.drop_table('plano_aplic')
    op.drop_table('pagamentospdctr')
    op.drop_table('pagamento')
    op.drop_table('msg_siconv')
    op.drop_table('grupo_programa_cnpq')
    op.drop_table('financeiro_acordo')
    op.drop_table('empenho')
    op.drop_table('emp_cap_cus')
    op.drop_table('desembolso')
    with op.batch_alter_table('users', schema='dem') as batch_op:
        batch_op.drop_index(batch_op.f('ix_dem_users_username'))
        batch_op.drop_index(batch_op.f('ix_dem_users_email'))

    op.drop_table('users', schema='dem')
    op.drop_table('tipos_demanda', schema='dem')
    op.drop_table('sistema', schema='dem')
    op.drop_table('plano_trabalho', schema='dem')
    op.drop_table('log_desc', schema='dem')
    with op.batch_alter_table('instrumento', schema='dem') as batch_op:
        batch_op.drop_index(batch_op.f('ix_dem_instrumento_sei'))

    op.drop_table('instrumento', schema='dem')
    op.drop_table('coords', schema='dem')
    with op.batch_alter_table('dados_sei', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dados_sei_sei'))

    op.drop_table('dados_sei')
    op.drop_table('crono_desemb')
    op.drop_table('convenio')
    op.drop_table('chamadas_cnpq_acordos')
    op.drop_table('chamadas_cnpq')
    op.drop_table('chamadas')
    op.drop_table('capital_custeio')
    op.drop_table('bolsas')
    with op.batch_alter_table('acordos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acordos_sei'))

    op.drop_table('acordos')
    # ### end Alembic commands ###
